### ISSUE TITLE
style header home link

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/apereo.foundation#32]
In https://getmdl.io they styled their header by adding an extra class with

```css
.class-name {
  text-decoration: none;
  color: rgb(255, 255, 255);
}
```
